### ISSUE TITLE
Get Coordinates when clicked on map

### ISSUE THREAD

**Issue by nhjariwala** [Mapwize/mapwize-ui-js#11]
Hello Mapwize,
Thanks for awesome service.

We want to add places dynamically into our indoor map. For instance we have setup 10 places from Mapwize studio and its working superb in android application; now I want to add places (not from Mapwize studio) from JS. Can we implement it? If yes, then how?

We have checked the API it has option to create a places but it require coordinates but we don't have it. We want something similar to mapwize studio means we can select a point on map and create places directly without coordinates. For example If we implement `mapwize-ui-JS` and it display the indoor map and when user select on map and we can get coordinates and then by using API we can create a place.

If coordinates known then we can create places and we tried it and it works, thus we need coordinates by selecting map. 

I will be waiting for your reply

Thanks

**Comment by Sparksx** [comment]
Hi, 

you can listen click event on the my with `map.on('mapwize:click', function (e) { console.log(e.lngLat)})`

Get more information in [the documentation](https://docs.mapwize.io/)
