### ISSUE TITLE
Searchbar text isn't updated on language change

### ISSUE THREAD

**Issue by samueldepooter** [Mapwize/mapwize-ui-js#177]
Tech stack:
- "react": "^16.0.0" (latest)
- "typescript": "^3.8.3" (latest)
- "mapwize-ui": "^2.5.0" (latest)

If you switch languages from within the UI, it translates the text inside the map but it won't translate the text inside the searchbar.

![image](https://user-images.githubusercontent.com/15377417/81267167-4d775c80-9046-11ea-9af3-6a28d324242b.png)

**Comment by Sparksx** [comment]
Hi @samueldepooter 

Thanks for your feedback
There's two concepts in mapwize ui:
- The language of all the ui elements (search bar, search result, ..)
- The language used by the map (to display venues content)

The first one is managed in this project by adding translation files ([`/src/locales`](https://github.com/Mapwize/mapwize-ui-js/tree/master/src/locales))
The second one is managed in the studio, directly by clients.

This selector only used to change the current venue language
To change the ui element languages, you've to use `mapwizeInstance.setLocale('en')`

You can link the two languages by adding:
```javascript
const supportedLanguages = mapwizeInstance.getLocales()
mapwizeInstance.on('mapwize:languagechange',(e) => {
  if (supportedLanguages.includes(e.language)) {
    mapwizeInstance.setLocal(e.language)
  } else {
    mapwizeInstance.setLocal('en') // universal fallback language
  }
})
```

**Comment by samueldepooter** [comment]
Thank you for your help, that seems to do the trick!

In case anyone comes across this: small typo but `mapwizeInstance.setLocal()` should be `mapwizeInstance.setLocale()`.
