### ISSUE TITLE
Published bundle is not compatible with IE11

### ISSUE THREAD

**Issue by RLejolivet** [Mapwize/mapwize-ui-js#30]
Hello,

The published (prod) bundle does not run on IE11 : it contains at least the `class` keywords that IE11 does not understand.

This is apparently fine for "recent" configurations, but at least one of our apps with a couple years old webpack configuration fails due to [this issue](https://github.com/babel/babel/issues/4125) when trying to run babel on the already-compiled mapwize-ui bundle, to remove the `class` keywords.  
Rather than trying to mess with my webpack config, I was able to make the application run by rebuilding mapwize-ui with adding the `@babel/preset-env` preset to `webpack.common.json` (no additional conf other than just adding the preset).

Is there any reason not to add this preset?

**Comment by mathieugerard** [comment]
Thanks for reporting Raphaël. If the preset-env is only improving compatibility, there should not be any reason not to use it. We'll check to make sure there is no side effect and apply the change.

What do you think @Sparksx ?

**Comment by Sparksx** [comment]
Hello,

I'll try to build the next release with `@babel/preset-env`
Don't know why we didn't enable it before

Thanks for your feedback

**Comment by Sparksx** [comment]
This has been resolved since version 2.0.0
