### ISSUE TITLE
Marker disappeared upon clicked (and the marker suddenly appeared elsewhere)

### ISSUE THREAD

**Issue by arkarwmh** [Mapwize/mapwize-ui-js#4]
Whenever I clicked on a Place, then a Marker appeared. And then upon clicking again on that Marker appeared, it then suddenly disappeared and then appears at somewhere else nearby. Probably at it's parent Building or Venue or something.

But certainly, the Marker on a Place cannot be maintained upon clicking.

Can try that on one of the mapwize demo venues:
https://maps.mapwize.io/#/v/mj_souk/1?z=18

Edited: We need this to be fixed because only then we can try further processing upon clicking on Markers (like, showing the popups, etc).

**Comment by arkarwmh** [comment]
(Demo) Screencast:
https://www.dropbox.com/s/abi9ttkixiw051m/mapwize-marker-click-bug.mov?dl=0

**Comment by Sparksx** [comment]
Hi, this issue is not linked to mapwize-ui-js.
The problem has been fixed and will be deployed soon

You can join us on intercom chat (on studio) if you encounter this problem again

**Comment by TomTronchet** [comment]
Hi, I got that bug too after ugrading mapwize from 3.2 to 4.1 using mapwize-ui.
I use a custom marker, every markers disapear after clicking on one marker in a venue.
Don't have this bug when I click on a marker without being inside a Venue.

What was the fix about this ?

**Comment by Sparksx** [comment]
Mapwize ui has is own click listenner that you cannot disable
When your are in a venue, a click on a place remove all the markers, select the place and add a marker on it

**Comment by TomTronchet** [comment]
Hi thanks a lot for the quick answer.
Why do you mean by 'select the place and add a marker on it', should I re-add marker at every click on a place ? Or there is a way to link markers to the place and they will not dissapear after a click ?
I added a popup (with mapbox-gl custom marker) to my marker so it's not possible to handle click on markers anymore ?

**Comment by Sparksx** [comment]
Mapwize ui does it itself.
Can you share me a jsfiddle example wich reproduce your problem (you can fork this one: https://jsfiddle.net/Mapwize/pdmrvckn/)

**Comment by TomTronchet** [comment]
Hi, I reproduce a small example of my issue thanks to your jsfiddle.
https://jsfiddle.net/q1bwrjzk/7/

**Comment by Sparksx** [comment]
I've done that: https://jsfiddle.net/Mapwize/7hafgLte/

But there is no way to disable the default map click event listener in mapwize-ui.
You have to use https://www.npmjs.com/package/mapwize if you want your own behavior

**Comment by TomTronchet** [comment]
Oh thanks a lot for the solution.
Your fiddle is enough for me to solve my issue.

Have a nice day :)

**Comment by TomTronchet** [comment]
Humm still got an issue, but if I understand well your answer it's impossible to not destroy all marker when user clicks anywhere in the place ?
